<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.mydemo</groupId>
        <artifactId>modules</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>mydemo-user</artifactId>
    <packaging>pom</packaging>
    <name>mydemo-user</name>
    <description>User 域聚合模块</description>

    <modules>
        <module>user-common</module>
        <module>user-service</module>
        <module>user-job</module>
        <module>user-consumer</module>
    </modules>

</project>
