<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.mydemo</groupId>
        <artifactId>my-spring-cloud-demo</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>common</artifactId>
    <packaging>pom</packaging>
    <name>common</name>
    <description>公共模块聚合</description>

    <modules>
        <module>common-model</module>
        <module>common-util</module>
        <module>common-config</module>
        <module>common-redis</module>
        <module>common-kafka</module>
        <module>common-web</module>
        <module>common-feign</module>
    </modules>

</project>
