# Nacos Namespace: dev
# Data ID: shared-kafka.yml  Group: DEFAULT_GROUP

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
